# Generated by Django 4.1.13 on 2023-11-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0030_merge_20231016_0118"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoteroEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zoteroId",
                    models.CharField(max_length=255, verbose_name="Zotero ID"),
                ),
                (
                    "shortTitle",
                    models.TextField(blank=True, null=True, verbose_name="Short title"),
                ),
                (
                    "fullCitation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Full Citation"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Year of publication"
                    ),
                ),
            ],
        ),
    ]
