# Generated by Django 4.1.13 on 2023-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0031_zoteroentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zoteroentry",
            name="year",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Year of publication",
            ),
        ),
    ]
