# Generated by Django 4.1.13 on 2024-03-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0034_alter_instancecopiedwrittendownatplace_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="zotero_ref",
            field=models.TextField(blank=True, null=True, verbose_name="Zotero"),
        ),
    ]
