# Generated by Django 4.1.13 on 2024-03-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0035_alter_instance_zotero_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="personstudentofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
    ]
