# Generated by Django 4.1.13 on 2024-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0038_persontranslatorofwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="persondirectpredecessorinlineageofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
        migrations.AddField(
            model_name="persondiscipleofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
        migrations.AddField(
            model_name="personreferswithnametotheviewsofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
        migrations.AddField(
            model_name="personreferswithoutnametotheviewsofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
        migrations.AddField(
            model_name="personrequestorofperson",
            name="subject_of_teaching",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="subject of teaching",
            ),
        ),
    ]
