# Generated by Django 4.1.13 on 2024-03-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0001_initial"),
        (
            "apis_ontology",
            "0039_persondirectpredecessorinlineageofperson_subject_of_teaching_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonAnnotatorOfWork",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "zotero_refs",
                    models.TextField(blank=True, null=True, verbose_name="Zotero"),
                ),
                (
                    "tei_refs",
                    models.TextField(blank=True, null=True, verbose_name="Excerpts"),
                ),
                (
                    "support_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Support notes"
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Positive", "Positive"),
                            ("Uncertain", "Uncertain"),
                            ("Negative", "Negative"),
                        ],
                        default="Positive",
                        max_length=1000,
                        null=True,
                        verbose_name="Confidence",
                    ),
                ),
                ("start_date", models.DateField(blank=True, editable=False, null=True)),
                (
                    "start_start_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "start_end_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                ("end_date", models.DateField(blank=True, editable=False, null=True)),
                (
                    "end_start_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "end_end_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "start_date_written",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Start"
                    ),
                ),
                (
                    "end_date_written",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="End"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
    ]
